apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Release.Name "appdynamics-operator" | trunc 63 }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: appdynamics-operator
spec:
  selector:
    matchLabels:
      control-plane: appdynamics-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: appdynamics-operator
    spec:
      containers:
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        args:
        - "--secure-listen-address=0.0.0.0:8443"
        - "--upstream=http://127.0.0.1:8080/"
        - "--logtostderr=true"
        - "--v=10"
        ports:
        - containerPort: 8443
          name: https
      - name: manager
        args:
        - --leader-elect
        image: {{ .Values.operatorPod.image }}
        imagePullPolicy: {{ .Values.operatorPod.imagePullPolicy }}
        env:
          - name: APPDYNAMICS_OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
        {{- toYaml .Values.operatorPod.resources | nindent 10 }}
      imagePullSecrets:
      {{- toYaml .Values.operatorPod.imagePullSecrets | nindent 8}}
      serviceAccountName: {{ .Values.operatorServiceAccount }}
      terminationGracePeriodSeconds: 10
