install:
  clustermon: true
  defaultInfraCollectors: true


# RBAC config
clustermonServiceAccount: appdynamics-clustermon
infraAgentServiceAccount: appdynamics-infraagent
otelServiceAccount: appdynamics-otel

#Clustermon Configs
# TODO: what configs do we expose?
clustermonConfig:
  clusterName: dev #Needs to be changed in prod
  enabled: "true"
  logLevel: info
  logFilesMaxSizeMb: 10
  logFilesNumBackups: 4
  printToStdout: "true"
  tickerInterval: 60 #TODO: does this need to be exposed?

  namespaceFilter:
    includeRegex: ".*"
    excludeRegex: ""

  entityFilter:
    excludeRegex: ""
    excludeLabels: []

  labelFilter:
    excludeRegex: ""

  testSetupEnabled: "false"
  optimisedPayloadInterval: -1

  events:
    enabled: ""
    severityToExclude: []
    reasonToExclude: []
    severeGroupByReason: []
    rateLimit: 1000

  ingressControllers: {}

#Infra Agent Configs
infraAgentConfig:
  logLevel: info
  logFilesMaxSizeMb: 10
  logFilesNumBackups: 4
  printToStdout: "true"
#TODO: What to expose out of the following?
#  exporterTransport
#  clientLibSendUrl
#  clientLibRecvUrl
#  requestTimeoutSeconds
#  httpClientTimeoutMs
#  collectorsConfScanIntervalSeconds
#  collectorsConfStaleGraceIntervalSeconds
#  debugEnabled
#  debugSendUrl
#  debugRecvUrl
#  fileExporterEnabled
#  fileExporterName
#  metricBatchSizeCount
#  logsBatchTimeoutSeconds
#  metricsBatchTimeoutSeconds
#  logsBatchSizeCount
#  proxyUrl
#  proxyUserName
#  proxyPassword
#  fileExporterMetricsOutputFile
#  fileExporterLogsOutputFile
#  fileExporterLogsEnabled
#  fileExporterMetricsEnabled
#  disableDefaultCollectors
#  receiverCaFile
#  receiverCertFile
#  receiverKeyFile
#  receiverPort

#Servermon Configs
servermonConfig:
  name: ServerMon
  gatherInterval: 10
  logLevel: info
  logFilesMaxSizeMb: 10
  logFilesNumBackups: 4
  skipProviderCheck: "true" #Set to false in prod
  #TODO: Figure out what properties need to be exposed
  #exporterAddress: %s
  #exporterPort: %d
  #dependency: %s
  #privileged: %s
  #installDependency: %s
  #defaultCollector: %s

#Containermon Configs
containermonConfig:
  name: ContainerMon
  gatherInterval: 10
  logLevel: info
  logFilesMaxSizeMb: 10
  logFilesNumBackups: 4
  #TODO: Figure out what properties need to be exposed
  #exporterAddress: %s
  #exporterPort: %d
  #dependency: %s
  #privileged: %s
  #installDependency: %s
  #defaultCollector: %s

#Deployment specific configs
clustermonPod:
  image: appdynamics/clustermon:latest #Needs to be changed in prod
  imagePullPolicy: Never #Needs to be changed in prod
  resources: {}
  labels: {}
  annotations: {}
  nodeSelector: {}
  imagePullSecrets: []
  affinity: {}
  tolerations: []
  securityContext: {}
  #  imageBaseUrl: appdynamics/clustermon
  #  versionsUrl: https://raw.githubusercontent.com/sahilranadive/appdynamics-charts/master/clustermon/versions.json
  #  autoUpdate: "true"

#Daemonset specific configs
inframonPod:
  image: appdynamics/clustermon:latest #Needs to be changed in prod
  imagePullPolicy: Never #Needs to be changed in prod
  resources: {}
  labels: {}
  annotations: {}
  nodeSelector: {}
  imagePullSecrets: []
  affinity: {}
  tolerations: []
  securityContext: {}


#Daemonset specific configs
otelCollectorPod:
  otelCollectorImage: dtr.corp.appdynamics.com/pavan.krishna/appdotelcol:0.36.0-21.10.0.49
  imagePullPolicy: Never #Needs to be changed in prod
  resources: {}
  labels: {}
  annotations: {}
  nodeSelector: {}
  imagePullSecrets: []
  affinity: {}
  tolerations: []
  securityContext: {}

otelCollector:
  hostPort: 8567
  apmNamespaces: "dev*|prod*|stage*"
  config:
    oauth2client:
      clientId: c3jmo9t4s56l5hr66aq0 #Set to null in prod
      clientSecret: tV4mFqajkoDsRw1O1Vt4nCT4gHIjgLd7SStRQoCHX7A #Set to null in prod
      authEndpoint: l4a-ce-authz.saas.appd-test.com #Set to null in prod
      # For dev purpose, leave tenantId unchanged, make changes to appDTenantId instead.
      tenantId: 19839a22-86c5-4050-aabe-846d3aec74b6 #Set to null in prod
      appDTenantId: 04e12784-1d04-4866-b136-39e01525b010 #TODO: Needs to be removed in the future
      timeout: "10s"
    httpMetricsEndpoint: https://alameda-lev.saas.appd-test.com/data/v1beta/metrics
    httpLogsEndpoint: https://alameda-lev.saas.appd-test.com/data/v1beta/logs
    httpTracesEndpoint: https://alameda-lev.saas.appd-test.com/data/v1beta/trace
    logLevel: "info"
    tls:
      insecure: "false"
      caFile: "/etc/otel/certs/ca/ca.pem"
      certFile: "/etc/otel/certs/receiver/server.pem"
      keyFile: "/etc/otel/certs/receiver/server-key.pem"
      minVersion: "1.2"