apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" .Release.Name "appdynamics-crd-validator" | trunc 63 }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ printf "%s-%s" .Release.Name "appdynamics-crd-validator" | trunc 63 }}
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: {{ .Values.operatorServiceAccount }}
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: {{ .Values.operatorPod.image }}
          imagePullPolicy: {{ .Values.operatorPod.imagePullPolicy }}
          command: ["/crd-validator"]
