operatorServiceAccount: appdynamics-operator
operatorPod:
  image: 494198612820.dkr.ecr.us-west-2.amazonaws.com/clustermon/appdynamics-operator-levitate:latest
  imagePullPolicy: Always
  imagePullSecrets:
  - name: aws-ecr-secret
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
