{{ if .Values.install.defaultInfraCollectors -}}
apiVersion: cluster.appdynamics.com/v1alpha1
kind: Inframon
metadata:
  name: {{ printf "%s-%s" .Release.Name "appdynamics-inframon" | trunc 63 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{ with .Values.inframonPod -}}
  image: {{ .image }}
  imagePullPolicy: {{ .imagePullPolicy }}
  resources:
  {{- toYaml .resources | nindent 4 }}
  labels:
  {{- toYaml .labels | nindent 4 }}
  annotations:
  {{- toYaml .annotations | nindent 4 }}
  nodeSelector:
  {{- toYaml .nodeSelector | nindent 4 }}
  imagePullSecrets:
  {{- toYaml .imagePullSecrets | nindent 4 }}
  affinity:
  {{- toYaml .affinity | nindent 4 }}
  tolerations: {{ .tolerations }}
  securityContext:
  {{- toYaml .securityContext | nindent 4 }}
  {{- end }}

  serviceAccountName: {{ .Values.inframonServiceAccount}}
  mTLSEnabled: {{ .Values.mTLSEnabled | quote }}

  {{ with .Values.infraManagerConfig -}}
  logFilesMaxSizeMb: {{ .logFilesMaxSizeMb }}
  logFilesNumBackups: {{ .logFilesNumBackups }}
  printToStdout: {{ .printToStdout | quote }}
  logLevel: {{ .logLevel }}
  #TODO: Add whatever properties are finalized to be exposed by Infra Manager
  {{- end }}
{{- end }}